# config_template.py — default template; copied to config.py by `make` on first build.
# Do NOT edit this file for local tuning — edit config.py instead.
# Edit this file only to change the project-wide defaults that get committed.

# ─── DIMM configuration ───────────────────────────────────────────────────────
# Check with: sudo dmidecode -t memory | grep -E "Speed|Configured"

DIMM_TRANSFER_RATE_MT_S = 5600   # e.g. DDR5-4800 → 4800, DDR4-3200 → 3200
DIMM_CHANNELS           = 1      # number of populated memory channels

# ─── NUMA configuration ──────────────────────────────────────────────────────
# Which NUMA node to use for both CPU affinity (-C) and memory allocation (-m).
# Check topology with: numactl --hardware

NUMA_NODE = 0

# ─── Hugepage configuration ───────────────────────────────────────────────────
# Number of 1GB hugepages to allocate as the benchmark region.
# - For randread_bw: must be a power of 2 (1, 2, 4, 8, ...) due to LFSR masking.
# - For stream_bw: any positive integer is fine.
# Check available pages with: grep HugePages /proc/meminfo
# Allocate with: sudo sh -c 'echo N > /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages'

HUGEPAGES_1GB = 4

# ─── Sweep configuration ─────────────────────────────────────────────────────

CORE_START = 1     # first core count to test
CORE_MAX   = 8    # last  core count to test  (None → use all CPUs in NUMA_NODE)
CORE_STEP  = 1     # increment between steps

ITERS_PER_THREAD = 100_000_000   # passed as 2nd arg to the binary

# Number of consecutive cachelines to fetch per random access (rand mode only).
# Start address is aligned to lines_per_access*64B so accesses never straddle block boundaries.
# Allowed values: 1, 2, 4, 8, 16  (default 1 = single cacheline, classic random-read behaviour)
# iters_per_thread counts total 64B cachelines, so total traffic is N-independent.
LINES_PER_ACCESS = 1

# How the LINES_PER_ACCESS cachelines of one random access are chosen (rand mode only):
#   0 = consecutive : addr, addr+64, addr+128, ...           (classic; N-independent traffic)
#   1 = samebank    : addr XOR'd with per-column-bit masks so all LINES_PER_ACCESS
#                     cachelines land in the same channel/rank/bank-group/bank/row,
#                     at adjacent columns (row-buffer-hit access pattern).
#                     Requires LINES_PER_ACCESS <= max columns supported by ADDR_MAP below.
ACCESS_MODE = 0

# Default DRAM address mapping for ACCESS_MODE=1 — a key into address_mapping.SYSTEMS.
# All registered SYSTEMS are compiled into the binary; this picks the DEFAULT used
# when the ACCESS_MAP env var is unset. To use another mapping at runtime WITHOUT
# rebuilding, run e.g.  ACCESS_MAP=<name> ./randread_bw ...  (sweep_bw.py passes this
# value automatically). See address_mapping.py to add mappings for other systems.
ADDR_MAP = "arrow_1ch_1dpc_1rank_16gb"

# ─── Misc ────────────────────────────────────────────────────────────────────

# Set to True if the binary needs sudo to allocate 1GB hugepages
USE_SUDO = False
