#!/usr/bin/env python3
"""Generate decode_masks.h from address_mapping.SYSTEMS.

latency_bw needs the *full* DRAM decode (channel/rank/bank_group/bank/row/col)
for arbitrary physical addresses obtained via /proc/self/pagemap — unlike
access_masks.h (gen_access_masks.py), which only emits column-step masks for
staying within one bank/row. This script emits the raw per-field masks from
address_mapping.SYSTEMS as a C header, plus a table of (address -> expected
decode) self-check vectors (computed here with address_mapping.decode()) so
the C++ decode() re-implementation can assert itself against the Python
reference at program startup.

Run manually with: python3 gen_decode_masks.py [-o decode_masks.h]
The Makefile also runs this automatically before building latency_bw.
"""

import argparse
import random
import sys

import config as cfg
import address_mapping as am

# Max number of XOR-parity masks needed for any single selector field
# (channel/rank/bank_group/bank) across all registered systems. Currently
# bank_group tops out at 3 masks; padded to 4 for headroom so adding a system
# with one more selector bit doesn't require touching the struct layout.
_computed_max = max(
    len(s[key])
    for s in am.SYSTEMS.values()
    for key in ("channel", "rank", "bank_group", "bank")
)
DECODE_MAX_BITS = max(_computed_max, 4)

NUM_SELFCHECK_PER_SYSTEM = 32
SELFCHECK_ADDR_BITS = 40  # generous upper bound; covers every mask's highest set bit


def gen_selfcheck_cases(name: str) -> list:
    rnd = random.Random(0)
    cases = []
    for _ in range(NUM_SELFCHECK_PER_SYSTEM):
        addr = rnd.getrandbits(SELFCHECK_ADDR_BITS) & ~0x3f  # cacheline-aligned
        d = am.decode(name, addr)
        cases.append((addr, d["channel"], d["rank"], d["bank_group"], d["bank"], d["row"], d["col"]))
    return cases


def field_line(masks: list) -> tuple:
    """Return (count, padded-mask-init-string) for one selector field."""
    if len(masks) > DECODE_MAX_BITS:
        sys.exit(f"decode_masks: field has {len(masks)} masks > DECODE_MAX_BITS={DECODE_MAX_BITS}")
    padded = list(masks) + [0] * (DECODE_MAX_BITS - len(masks))
    inits = ", ".join(f"0x{m:x}ULL" for m in padded)
    return len(masks), inits


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-o", "--output", default="decode_masks.h",
                         help="output header path (default: decode_masks.h)")
    args = parser.parse_args()

    default = cfg.ADDR_MAP
    if default not in am.SYSTEMS:
        sys.exit(
            f"config.ADDR_MAP={default!r} not found in address_mapping.SYSTEMS "
            f"(available: {', '.join(sorted(am.SYSTEMS))})"
        )

    map_entries = []
    selfcheck_entries = []
    for name in sorted(am.SYSTEMS):
        s = am.SYSTEMS[name]
        n_channel, channel_init = field_line(s["channel"])
        n_rank, rank_init = field_line(s["rank"])
        n_bg, bg_init = field_line(s["bank_group"])
        n_bank, bank_init = field_line(s["bank"])
        map_entries.append(
            f'    {{ "{name}", {s["offset_bits"]},\n'
            f'      {n_channel}, {{ {channel_init} }},\n'
            f'      {n_rank}, {{ {rank_init} }},\n'
            f'      {n_bg}, {{ {bg_init} }},\n'
            f'      {n_bank}, {{ {bank_init} }},\n'
            f'      0x{s["row"]:x}ULL, 0x{s["column"]:x}ULL }}'
        )
        for addr, ch, rk, bg, bank, row, col in gen_selfcheck_cases(name):
            selfcheck_entries.append(
                f'    {{ "{name}", 0x{addr:x}ULL, {ch}, {rk}, {bg}, {bank}, 0x{row:x}ULL, 0x{col:x}ULL }}'
            )

    maps_table = ",\n".join(map_entries)
    selfcheck_table = ",\n".join(selfcheck_entries)

    header = f"""// AUTO-GENERATED by gen_decode_masks.py from address_mapping.SYSTEMS.
// Do not edit by hand — re-run gen_decode_masks.py (the Makefile does this
// automatically whenever config.py or address_mapping.py change).
#pragma once
#include <cstdint>

// DECODE_MAX_BITS bounds the channel/rank/bank_group/bank mask arrays below.
// Computed as max(len(field)) across every registered SYSTEMS entry (currently
// {_computed_max}), padded up to {DECODE_MAX_BITS} for headroom.
#define DECODE_MAX_BITS {DECODE_MAX_BITS}

// Default map used at runtime when the ACCESS_MAP env var is unset (== config.ADDR_MAP).
#define DECODE_DEFAULT_MAP "{default}"
// Default hugepage pool size in 1GB pages (== config.HUGEPAGES_1GB).
#define DECODE_DEFAULT_HUGEPAGES {cfg.HUGEPAGES_1GB}

struct DecodeMap {{
    const char *name;
    int         offset_bits;
    // Each n_X-length prefix of X[] is a list of XOR-parity masks; the i-th
    // mask produces output bit i of that selector (see address_mapping.py's
    // module docstring for the semantics this mirrors).
    int         n_channel;    uint64_t channel[DECODE_MAX_BITS];
    int         n_rank;       uint64_t rank[DECODE_MAX_BITS];
    int         n_bank_group; uint64_t bank_group[DECODE_MAX_BITS];
    int         n_bank;       uint64_t bank[DECODE_MAX_BITS];
    // row/col: single bit-gather masks (set bits packed LSB-first).
    uint64_t    row_mask;
    uint64_t    col_mask;
}};

static const DecodeMap DECODE_MAPS[] = {{
{maps_table}
}};
static const int DECODE_NUM_MAPS = (int)(sizeof(DECODE_MAPS) / sizeof(DECODE_MAPS[0]));

// Self-check vectors: (system, addr) -> expected decode(), computed by the
// Python reference implementation (address_mapping.decode()). latency_bw
// asserts its C++ decode() reproduces every case for the selected map at
// startup, catching any port mismatch before it silently corrupts results.
struct DecodeSelfCheck {{
    const char *name;
    uint64_t    addr;
    int         channel;
    int         rank;
    int         bank_group;
    int         bank;
    uint64_t    row;
    uint64_t    col;
}};

static const DecodeSelfCheck DECODE_SELFCHECKS[] = {{
{selfcheck_table}
}};
static const int DECODE_NUM_SELFCHECKS = (int)(sizeof(DECODE_SELFCHECKS) / sizeof(DECODE_SELFCHECKS[0]));
"""
    with open(args.output, "w") as f:
        f.write(header)

    print(f"wrote {args.output}  ({len(map_entries)} map(s), default={default}, "
          f"{NUM_SELFCHECK_PER_SYSTEM} self-check vectors/map)")


if __name__ == "__main__":
    main()
