#!/usr/bin/env python3
"""Generate access_masks.h from the ADDR_MAP selected in config.py.

randread_bw's ACCESS_MODE=1 ("samebank") walks LINES_PER_ACCESS adjacent
columns of the same channel/rank/bank-group/bank/row by XOR-ing a randomly
picked cacheline address with a small set of per-column-bit masks. This
script computes those masks via address_mapping.col_step_masks() for
whichever system is selected by config.ADDR_MAP, verifies them against
address_mapping.decode(), and emits them as a C header consumed by
randread_bw.cpp.

Run manually with: python3 gen_access_masks.py [-o access_masks.h]
The Makefile also runs this automatically before building randread_bw.
"""

import argparse
import random
import sys

import config as cfg
import address_mapping as am

# LINES_PER_ACCESS tops out at 16 (see config_template.py), which needs 4
# column bits (2**4 == 16); no point solving for more.
MAX_COL_BITS = 4


def self_check(name: str, masks: list) -> None:
    """Verify each mask changes only the intended column bit, leaving
    channel/rank/bank_group/bank/row untouched, across random addresses."""
    rnd = random.Random(0)
    for _ in range(256):
        base = rnd.getrandbits(36) & ~0x3f  # cacheline-aligned test address
        d0 = am.decode(name, base)
        for i, mask in enumerate(masks):
            d1 = am.decode(name, base ^ mask)
            for key in ("channel", "rank", "bank_group", "bank", "row"):
                if d0[key] != d1[key]:
                    sys.exit(
                        f"address_mapping self-check failed: system={name!r} "
                        f"col_bit={i} mask=0x{mask:x} changed {key} "
                        f"({d0[key]} -> {d1[key]}) at addr=0x{base:x}"
                    )
            if d1["col"] != (d0["col"] ^ (1 << i)):
                sys.exit(
                    f"address_mapping self-check failed: system={name!r} "
                    f"col_bit={i} mask=0x{mask:x} did not toggle only column "
                    f"bit {i} (col {d0['col']} -> {d1['col']}) at addr=0x{base:x}"
                )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-o", "--output", default="access_masks.h",
                         help="output header path (default: access_masks.h)")
    args = parser.parse_args()

    name = cfg.ADDR_MAP
    if name not in am.SYSTEMS:
        sys.exit(
            f"config.ADDR_MAP={name!r} not found in address_mapping.SYSTEMS "
            f"(available: {', '.join(sorted(am.SYSTEMS))})"
        )

    masks = am.col_step_masks(name, max_bits=MAX_COL_BITS)
    if not masks:
        sys.exit(f"address_mapping: system {name!r} has no solvable column bits")
    self_check(name, masks)

    mask_lines = ",\n".join(f"    0x{m:x}ULL" for m in masks)
    header = f"""// AUTO-GENERATED by gen_access_masks.py from address_mapping.SYSTEMS[{name!r}].
// Do not edit by hand — re-run gen_access_masks.py (the Makefile does this
// automatically whenever config.py or address_mapping.py change).
#pragma once
#include <cstdint>

#define ACCESS_MAP_NAME "{name}"
#define ACCESS_NUM_COL_BITS {len(masks)}

// ACCESS_COL_STEP_MASK[i] toggles column bit i only, preserving
// channel/rank/bank_group/bank/row. XOR together the masks for the set
// bits of d (0 <= d < 2**ACCESS_NUM_COL_BITS) to step the column by d.
static const uint64_t ACCESS_COL_STEP_MASK[ACCESS_NUM_COL_BITS] = {{
{mask_lines}
}};
"""
    with open(args.output, "w") as f:
        f.write(header)

    print(f"wrote {args.output}  (system={name}, {len(masks)} column bit(s), "
          f"max lines_per_access={1 << len(masks)})")


if __name__ == "__main__":
    main()
