# config_template.py — default template; copied to config.py by `make` on first build.
# Do NOT edit this file for local tuning — edit config.py instead.
# Edit this file only to change the project-wide defaults that get committed.

# ─── DIMM configuration ───────────────────────────────────────────────────────
# Check with: sudo dmidecode -t memory | grep -E "Speed|Configured"

DIMM_TRANSFER_RATE_MT_S = 5600   # e.g. DDR5-4800 → 4800, DDR4-3200 → 3200
DIMM_CHANNELS           = 1      # number of populated memory channels

# ─── NUMA configuration ──────────────────────────────────────────────────────
# Which NUMA node to use for both CPU affinity (-C) and memory allocation (-m).
# Check topology with: numactl --hardware

NUMA_NODE = 0

# ─── Hugepage configuration ───────────────────────────────────────────────────
# Number of 1GB hugepages to allocate as the benchmark region.
# - For randread_bw: must be a power of 2 (1, 2, 4, 8, ...) due to LFSR masking.
# - For stream_bw: any positive integer is fine.
# Check available pages with: grep -i huge /proc/meminfo
# Allocate with: sudo sh -c 'echo N > /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages'

HUGEPAGES_1GB = 4

# ─── Sweep configuration ─────────────────────────────────────────────────────

CORE_START = 1     # first core count to test
CORE_MAX   = 8    # last  core count to test  (None → use all CPUs in NUMA_NODE)
CORE_STEP  = 1     # increment between steps

ITERS_PER_THREAD = 100_000_000   # passed as 2nd arg to the binary

# Number of consecutive cachelines to fetch per random access (rand mode only).
# Start address is aligned to lines_per_access*64B so accesses never straddle block boundaries.
# Allowed values: 1, 2, 4, 8, 16  (default 1 = single cacheline, classic random-read behaviour)
# iters_per_thread counts total 64B cachelines, so total traffic is N-independent.
LINES_PER_ACCESS = 1

# How the LINES_PER_ACCESS cachelines of one random access are chosen (rand mode only):
#   0 = consecutive : addr, addr+64, addr+128, ...           (classic; N-independent traffic)
#   1 = samebank    : addr XOR'd with per-column-bit masks so all LINES_PER_ACCESS
#                     cachelines land in the same channel/rank/bank-group/bank/row,
#                     at adjacent columns (row-buffer-hit access pattern).
#                     Requires LINES_PER_ACCESS <= max columns supported by ADDR_MAP below.
ACCESS_MODE = 0

# Default DRAM address mapping for ACCESS_MODE=1 — a key into address_mapping.SYSTEMS.
# All registered SYSTEMS are compiled into the binary; this picks the DEFAULT used
# when the ACCESS_MAP env var is unset. To use another mapping at runtime WITHOUT
# rebuilding, run e.g.  ACCESS_MAP=<name> ./randread_bw ...  (sweep_bw.py passes this
# value automatically). See address_mapping.py to add mappings for other systems.
ADDR_MAP = "arrow_1ch_1dpc_1rank_16gb"

# ─── DRAM hole (sub-4GB MMIO remap) ──────────────────────────────────────────
# The BIOS maps DRAM *around* the MMIO region below 4GB, so the address the
# memory controller decodes is not the system physical address from
# /proc/self/pagemap — everything above the hole is shifted down by its size:
#
#     dram_addr = phys >= DRAM_HOLE_END ? phys - (DRAM_HOLE_END - DRAM_HOLE_START)
#                                       : phys
#
# Skipping this makes decode() wrong for addresses whose high bits borrow
# across the subtraction, silently mislabelling them (e.g. a same-bank pair
# that is really in two different banks). The shift is arithmetic, so it CANNOT
# be folded into the XOR masks in address_mapping.py — it must be applied to
# each address before decoding.
#
# DRAM_HOLE_START is TOLUD: where DRAM stops and MMIO begins below 4GB. Find it
# as the first MMIO entry (PCI ECAM is often lower than the first "PCI Bus"):
#     sudo awk -F' : ' '/^[0-9a-f]/' /proc/iomem | head -40
# Cross-check: (4GB - DRAM_HOLE_START) + (top of RAM - 4GB) should equal the
# installed DIMM capacity exactly.
# Set DRAM_HOLE_START = DRAM_HOLE_END to disable the correction.

DRAM_HOLE_START = 0x80000000    # TOLUD — first MMIO address below 4GB
DRAM_HOLE_END   = 0x100000000   # 4GB

# ─── Hugepage channel balancing ──────────────────────────────────────────────
# A channel XOR function whose bits are ALL >= 30 is constant across a whole 1GB
# hugepage (e.g. cascade_4ch_1dpc_2rank_32gb's channel[1] = 0x1000000000, bit
# 36), so one hugepage only reaches half the channels and a plain mmap() can
# hand the benchmark a region that sits entirely on one side of that bit.
#
# BALANCE_HUGEPAGES makes randread_bw/stream_bw probe candidate hugepages
# through a hugetlb memfd, pick equally many of each channel class, and map them
# so consecutive 1GB slots in VA alternate classes. Mappings whose channel bits
# all live below bit 30 need none of this — the option then reports that and
# takes the plain path.
#
# Both options read /proc/self/pagemap, which requires root — set USE_SUDO=True
# below (or run the binaries under sudo). Without root they print a warning and
# fall back to the plain mmap path.

BALANCE_HUGEPAGES    = True   # channel-balanced + VA-interleaved hugepage selection
PRINT_HUGEPAGE_ADDRS = True   # dump each hugepage's virtual/physical address + class

# ─── Misc ────────────────────────────────────────────────────────────────────

# Set to True if the binary needs sudo to allocate 1GB hugepages
# (also required by BALANCE_HUGEPAGES / PRINT_HUGEPAGE_ADDRS above)
USE_SUDO = True
